# Site settings
title: "Relearning"
motto: "Strive for success not for perfection"
email: fernandorsl@gmail.com
description: "All things mobile"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://fernandorocha.io" # the base hostname & protocol for your site
twitter_username: fernando_rochas
github_username:  rochabr
linkedin_link: https://br.linkedin.com/in/fernandorochas

# Build settings
markdown: kramdown

# Settings for comments helper
# Set 'provider' to the comment provider you want to use.
# Set 'provider' to false to turn commenting off globally.
comments :
  provider : facebook
  facebook :
    appid : 438383169701164
    num_posts: 5
    width: 580
    colorscheme: light

analytics :
  provider : google
  google : 
      tracking_id : 'UA-73706672-1'